//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace k.Content.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_GB {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_GB() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("k.Content.Language.en-GB", typeof(en_GB).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error: {0}.
        /// </summary>
        internal static string M00000_1 {
            get {
                return ResourceManager.GetString("M00000_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load credential: ID not found..
        /// </summary>
        internal static string M00001_0 {
            get {
                return ResourceManager.GetString("M00001_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credential expired..
        /// </summary>
        internal static string M00002_0 {
            get {
                return ResourceManager.GetString("M00002_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bucket is limited {0} columns..
        /// </summary>
        internal static string M00003_1 {
            get {
                return ResourceManager.GetString("M00003_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bucket is limited {0} rows..
        /// </summary>
        internal static string M00004_1 {
            get {
                return ResourceManager.GetString("M00004_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The encrypted password is not valid..
        /// </summary>
        internal static string M00005_0 {
            get {
                return ResourceManager.GetString("M00005_0", resourceCulture);
            }
        }
    }
}
