//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace k.sap.di.Content.Queries {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CUFD {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CUFD() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("k.sap.di.Content.Queries.CUFD", typeof(CUFD).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT	 TOP 1
        ///		 &quot;FieldID&quot;
        ///		,&quot;AliasID&quot;
        ///		,&quot;Descr&quot;
        ///		,Dflt
        ///		,NotNull
        ///--#msql		,&quot;TypeID&quot; + &quot;EditType&quot; as &quot;MyTypeID&quot;
        ///--#hana		,&quot;TypeID&quot; | &quot;EditType&quot; as &quot;MyTypeID&quot;
        ///FROM CUFD 
        ///WHERE	 Sys = &apos;N&apos;
        ///	AND	 &quot;TableID&quot; = {0}
        ///	AND	 &quot;AliasID&quot; = {1}.
        /// </summary>
        internal static string FieldIDInfor_2 {
            get {
                return ResourceManager.GetString("FieldIDInfor_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT	 UFD1.&quot;FldValue&quot;
        ///		,UFD1.&quot;Descr&quot;
        ///FROM	 UFD1
        ///WHERE	 UFD1.&quot;TableID&quot; = {0}
        ///	AND	 UFD1.&quot;FieldID&quot; = {1}.
        /// </summary>
        internal static string ValidValues_2 {
            get {
                return ResourceManager.GetString("ValidValues_2", resourceCulture);
            }
        }
    }
}
